Applying official almu CSS style to wyborca.html
almucode/c3po pull request #1
Opened 2019-11-10 23:22 UTC by rimelynx

Dodanie stylu identycznego jak oficjalna strona klubu do wyborca.html.

Użyte frameworki:
- W3.CSS 4 https://www.w3schools.com/w3css/
- Font Awesome 5 Free https://fontawesome.com/

2019-11-11 01:04 UTC, almucode requested changes
Bardzo mi się podoba nowa struktura dokumentu i poprawiony oraz rozbudowany tekst. Niestety ilość CSSa przyprawia mnie o zawrót głowy gdy wyobrażę sobie debugowanie tego. Możemy CSS okroić do tego co jest potrzebne, a najlepiej zintegrować tak aby i HTML i CSS były czytelne?

Jak byś opublikował swój branch jako GitHub Page, to chętnie bym się pobawił Twoją wersją na żywo.

2019-11-11 01:04 UTC, almucode commented on wyborca.html
> +    <link rel="stylesheet" href="css/font-awesome.all.min.css">
O ile dobrze rozumiem to z tych 50k+ CSSa potrzebujemy trzy ikonki. Możemy te fragmenty po prostu wyciągnąć? Całość sprowadza się do trywialnego dodania literki w odpowiednim foncie przed tekstem na przycisku, nie?

2019-11-11 01:04 UTC, almucode commented on wyborca.html
> +    <link rel="stylesheet" href="css/w3.css">
O ile dobrze rozumiem to z tego 20k+ CSSa potrzebujemy 7-8 raczej trywialnych pozycji. Możemy je wyciąć albo nawet zintegrować z głównym CSSem?

2019-11-11 01:04 UTC, almucode commented on wyborca.html
> +          <form id="vote" class="almu-vote-form">
Czemu ten formularz traktujemy specjalnie? Nie możemy po prostu ustawić reguł dla wszystkich formularzy?

2019-11-11 01:04 UTC, almucode commented on wyborca.html
> +        <h1 class="">C3PO - Wyborca</h1>
Czemu klasa jest pusta?

2019-11-11 09:27 UTC, almucode requested changes
Jeszcze parę komentarzy :-)

2019-11-11 09:27 UTC, almucode commented on css/main.css
> +	font-size: 16px;
Jeśli dobrze rozumiem, to robimy reset CSSa (reset.css), żeby go potem znormalizować (początek w3.css; po resecie ma to ograniczony sens), żeby potem ustalić standardowe rozmiary (główna część w3.css; nie wiem po co nam reset i normalizacja skoro w3.css i tak wszystko ustala), po czym je poprawić (tutaj; czyli wybraliśmy framework W3, a później i tak jesteśmy mądrzejsi). Trochę to nadmiarowe. Zamiast tego proponowałbym jedną z dwóch strategii:
1. Po prostu opieramy się na wbudowanych stylach każdej przeglądarki i zmieniamy to co nam potrzebne.
2. Robimy normalizację wbudowanych stylów przeglądarki, a później dostosowujemy to co nam nie odpowiada.

Reset i budowanie stylu od zera wydaje mi się bez sensu w dzisiejszych czasach.

2019-11-11 09:27 UTC, almucode commented on css/main.css
> +.almu-form-placeholder:not(:first-child) {
Ładny trik, ale JavaScript i tak czyści całą zawartość formularza przez zbudowaniem nowego, więc chyba nie ma potrzeby niczego chować CSSem.

2019-11-11 09:27 UTC, almucode commented on wyborca.html
> +            <button id="encrypt" class="w3-block">
W oryginalnej wersji rozróżniane są przyciski zwykłe i te do wysłania formularza. Jest to konieczne by formularz odpowiednio się wysyłał przy korzystaniu z klawiatury. Kliknięcie opcji po czym wciśnięcie Enter powinno od razu zaszyfrować głos.

2019-11-11 10:45 UTC, rimelynx commented on wyborca.html
> +    <link rel="stylesheet" href="css/font-awesome.all.min.css">
font-awesome.all.min.css zastąpiłem znacznie okrojonym fa.lean.css

2019-11-11 10:47 UTC, rimelynx commented on wyborca.html
> +    <link rel="stylesheet" href="css/w3.css">
w3.css przeszło w w3.lean.css
Na razie usunąłem tylko klasy kolorów (mamy swoje, ładniejsze) i kilka filtrów obrazków.
Tu na pewno da się jeszcze znacznie zmniejszyć rozmiar pliku.

2019-11-11 11:04 UTC, rimelynx commented on css/main.css
> +	font-size: 16px;
Nie jestem pewien, czy dobrze rozumiem.
Moje intencje to dokładnie opcja 2), wbudowane style niektórych przeglądarek są po prostu brzydkie ;)

reset.css normalizuje o wiele więcej własności niż później ustalamy w w3.css czy main.css (np. marginesy i wyłożenie). Fakt, reset.css stworzony jest głównie z myślą o mniej standardowych i nieco nieprzewidywalnych przeglądarkach (głównie na urządzenia mobilne) i mi osobiście daje niejako spokój ducha :)

Rozdzielenie stylów odnoszących się do tych samych elementów pomiędzy trzy różne pliki odzwierciedla logiczny podział według tego co te reguły mają na celu (reset - normalizacja, w3 - ogólny framework i responsywność, main - "skórka" i cała reszta rzeczy specyficznych dla tego projektu. Idąc dalej za tą logiką kusiło mnie nawet żeby rozdzielić "skórkę" i całą resztę, ale się powstrzymałem. ;)

2019-11-11 11:33 UTC, almucode commented on css/main.css
> +	font-size: 16px;
Jeśli robimy normalizację to nie wiem po co reset, tu jest dobry artykuł na ten temat: https://pineco.de/a-brief-about-css-reset-and-normalize/

Nie wiem czy dla naszego projektu normalizacja jest konieczna, ale jeśli tak to może po prostu użyć czegoś w miarę małego i świeżego jak https://github.com/csstools/normalize.css ?

W3CSS to fajny framework, ale my go tutaj prawie nie używamy. Wykorzystujemy normalizację, którą można załatwić osobno i parę elementów, które i tak są sensowne po normalizacji. Te szczegóły których potrzebujemy spokojnie można zintegrować w skórce i moim zdaniem będzie to bardziej czytelne. Np. nikt nie będzie musiał pamiętać by używać paru magicznych klas na wybranych elementach.

2019-11-15 23:41 UTC, almucode commented on wyborca.html
> +    <link rel="stylesheet" href="css/font-awesome.all.min.css">
Ikony zostały zintegrowane w icons.css

2019-11-15 23:44 UTC, almucode commented on wyborca.html
> +    <link rel="stylesheet" href="css/w3.css">
Z najnowszego Twojego merga wyciąłem diffa i wrzuciłem jako almu.css. Poza ramką fieldseta która wygląda jak bug, wygląda identycznie jak w Twoim forku (porównywałem side-by-side).

2019-11-15 23:47 UTC, almucode commented
Zrobiłem cherrypick istotnych zmian i CSS z ostatniego merga skumulowałem w almu.css.

Demo:
https://almucode.github.io/c3po/wyborca.html?skin=almu
https://almucode.github.io/c3po/komisja.html?skin=almu

Czyli myślę że ten pull request możemy zamknąć i ewentualne dalsze prace robić z heada.

2019-11-15 23:47 UTC, closed without merging